[package]
name = "docker_container_network_fix"
version = "0.1.0"
edition = "2021"

[dependencies]
bollard = "0.17.1"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
async-process = "2.3.0"
futures-lite = "2.5.0"
